# normalized style
hard_tabs = true
max_width = 120
match_block_trailing_comma = true
imports_granularity = "Crate"
newline_style = "Unix"
overflow_delimited_expr = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true

# apply as broadly as possible
error_on_unformatted = true
format_macro_matchers = true
format_strings = true

# comments
wrap_comments = true
comment_width = 120
format_code_in_doc_comments = true
normalize_comments = true
normalize_doc_attributes = true
